# Generated by Django 5.2.17 on 2026-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0014_sicor_dominios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontesincronizacao',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando na fila'), ('VERIFICANDO', 'Verificando fonte'), ('BAIXANDO', 'Baixando'), ('VALIDANDO', 'Validando'), ('IMPORTANDO', 'Importando'), ('CONCLUIDO', 'Concluído'), ('SEM_ALTERACAO', 'Sem alteração'), ('FALHOU', 'Falhou')], db_index=True, default='AGUARDANDO', max_length=30),
        ),
        migrations.AlterField(
            model_name='sicoroperacao',
            name='id',
            field=models.BigAutoField(db_column='_id', primary_key=True, serialize=False),
        ),
    ]
