# Generated by Django 5.2.17 on 2026-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0015_alter_fontesincronizacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fonte',
            field=models.CharField(choices=[('SICAR', 'SICAR'), ('IBAMA', 'IBAMA'), ('ICMBIO', 'ICMBio'), ('CNUC', 'CNUC'), ('PRODES', 'INPE / PRODES'), ('INCRA', 'INCRA'), ('SICOR', 'SICOR / Glebas'), ('SICOR_OPERACOES', 'Operações SICOR'), ('SICOR_DOMINIOS', 'Domínios SICOR'), ('SIGEF', 'SIGEF / INCRA'), ('SNCR', 'SNCR / INCRA'), ('FUNAI', 'FUNAI / Terras Indígenas'), ('FLORESTAS_PUBLICAS', 'Florestas Públicas'), ('DETER', 'INPE / DETER'), ('ANA', 'ANA / Outorgas'), ('ANM', 'ANM / Processos Minerários'), ('ZARC', 'ZARC'), ('MAPBIOMAS', 'MapBiomas'), ('FOCOS_CALOR', 'INPE / Focos de Calor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='camadaimportada',
            name='fonte',
            field=models.CharField(choices=[('SICAR', 'SICAR'), ('IBAMA', 'IBAMA'), ('ICMBIO', 'ICMBio'), ('CNUC', 'CNUC'), ('PRODES', 'INPE / PRODES'), ('INCRA', 'INCRA'), ('SICOR', 'SICOR / Glebas'), ('SICOR_OPERACOES', 'Operações SICOR'), ('SICOR_DOMINIOS', 'Domínios SICOR'), ('SIGEF', 'SIGEF / INCRA'), ('SNCR', 'SNCR / INCRA'), ('FUNAI', 'FUNAI / Terras Indígenas'), ('FLORESTAS_PUBLICAS', 'Florestas Públicas'), ('DETER', 'INPE / DETER'), ('ANA', 'ANA / Outorgas'), ('ANM', 'ANM / Processos Minerários'), ('ZARC', 'ZARC'), ('MAPBIOMAS', 'MapBiomas'), ('FOCOS_CALOR', 'INPE / Focos de Calor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='importacao',
            name='fonte',
            field=models.CharField(choices=[('SICAR', 'SICAR'), ('IBAMA', 'IBAMA'), ('ICMBIO', 'ICMBio'), ('CNUC', 'CNUC'), ('PRODES', 'INPE / PRODES'), ('INCRA', 'INCRA'), ('SICOR', 'SICOR / Glebas'), ('SICOR_OPERACOES', 'Operações SICOR'), ('SICOR_DOMINIOS', 'Domínios SICOR'), ('SIGEF', 'SIGEF / INCRA'), ('SNCR', 'SNCR / INCRA'), ('FUNAI', 'FUNAI / Terras Indígenas'), ('FLORESTAS_PUBLICAS', 'Florestas Públicas'), ('DETER', 'INPE / DETER'), ('ANA', 'ANA / Outorgas'), ('ANM', 'ANM / Processos Minerários'), ('ZARC', 'ZARC'), ('MAPBIOMAS', 'MapBiomas'), ('FOCOS_CALOR', 'INPE / Focos de Calor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loteimportacao',
            name='fonte',
            field=models.CharField(choices=[('SICAR', 'SICAR'), ('IBAMA', 'IBAMA'), ('ICMBIO', 'ICMBio'), ('CNUC', 'CNUC'), ('PRODES', 'INPE / PRODES'), ('INCRA', 'INCRA'), ('SICOR', 'SICOR / Glebas'), ('SICOR_OPERACOES', 'Operações SICOR'), ('SICOR_DOMINIOS', 'Domínios SICOR'), ('SIGEF', 'SIGEF / INCRA'), ('SNCR', 'SNCR / INCRA'), ('FUNAI', 'FUNAI / Terras Indígenas'), ('FLORESTAS_PUBLICAS', 'Florestas Públicas'), ('DETER', 'INPE / DETER'), ('ANA', 'ANA / Outorgas'), ('ANM', 'ANM / Processos Minerários'), ('ZARC', 'ZARC'), ('MAPBIOMAS', 'MapBiomas'), ('FOCOS_CALOR', 'INPE / Focos de Calor')], db_index=True, max_length=20),
        ),
    ]
